vim.api.nvim_set_keymap("n", "0", "^", { noremap = true, desc = "Move to the first non-whitespace character" })
vim.api.nvim_set_keymap("n", "<C-d>", "<C-d>zz", { noremap = true, desc = "Scroll down and center the buffer" })
vim.api.nvim_set_keymap("n", "<C-u>", "<C-u>zz", { noremap = true, desc = "Scroll up and center the buffer" })
vim.api.nvim_set_keymap("n", "<leader>l", "<cmd>nohlsearch<cr><cmd>echo ''<cr>", { desc = "Clear search and message" })
vim.api.nvim_set_keymap("n", "<leader>q", ":quit<cr>", { desc = "Quit", silent = true })
vim.api.nvim_set_keymap("n", "Q", "<nop>", { noremap = true, desc = "Disabled" })
vim.api.nvim_set_keymap("n", "j", "gj", { noremap = true, desc = "Move to next display line" })
vim.api.nvim_set_keymap("n", "k", "gk", { noremap = true, desc = "Move to previous display line" })
vim.api.nvim_set_keymap("t", "<C-t><esc>", "<C-\\><C-n>", { desc = "Exit insert model in the terminal" })
